version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/packages/*"
      - "/playground"
      - "/website"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 3
    open-pull-requests-limit: 20
    labels:
      - "dependencies"
      - "npm"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
